version: "3.8"
services:
  db:
    image: postgres
    container_name: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/log/db:/logs
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - project_network

  api:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./api:/app/api
      - gem_cache:/usr/local/bundle/gems
    depends_on:
      - db
    env_file: .env
    environment:
      RAILS_ENV: ${RAILS_ENV}
    networks:
      - project_network

  frontend:
    container_name: ${FRONT_APP_NAME}
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - ${FRONT_APP_PORT}:${FRONT_APP_PORT}
    volumes:
      - ./client:/app/client
      - node_modules:/app/client/node_modules
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}

volumes:
  gem_cache:
  db_data:
  node_modules:

networks:
  project_network:
