name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker-compose up --build -d
      - name: test_api
        run: docker-compose run -e "RAILS_ENV=test" --rm api
      - name: test_frontend
        run: docker-compose run -e "FRONT_MODE=test" --rm frontend
